from sqlalchemy.orm import Session
from ..llm.schema import LLMRuleFeedback, LLMRuleEvaluation
from ..models.feedback import Feedback
from ..models.fulfillment import Fulfillment
from ..models.submission import Submission
from ..models.rule_feedback_submission import RuleFeedbackSubmission
from ..models.rule import Rule
from ..schemas.feedback import InteractiveFeedbackResponse
from ..repository.rule import retrieve_by_id
from ..utils.logger import logger


def generate_initial_interactive_mode_feedbacks(
    db: Session,
    rules: list,
    llm_rule_feedbacks: list[LLMRuleFeedback],
    submission: Submission,
) -> list[Feedback]:
    llm_feedbacks_by_rule = {f.rule_name: f for f in llm_rule_feedbacks}

    feedbacks: list[Feedback] = []
    logger.info("Creating feedback objects...")
    for rule_id, rule_name, _ in rules:
        logger.info(f"Rule name {rule_name}")
        llm_rule_feedback = llm_feedbacks_by_rule.get(rule_name)
        if not llm_rule_feedback:
            continue
        feedback = Feedback(
            feedback_text=_create_interactive_feedback_text(llm_rule_feedback),
            initially_fulfilled=_is_rule_initially_fulfilled(llm_rule_feedback),
            rule_id=rule_id,
        )
        db.add(feedback)
        feedbacks.append(feedback)

    # flush will add all of the autogenerated fields to our list before committing
    db.flush()
    db.commit()

    logger.info("Creating rule feedback submission objects...")
    for feedback in feedbacks:
        rule_feedback_submission = RuleFeedbackSubmission(
            rule_id=feedback.rule_id,
            submission_id=submission.id,
            feedback_id=feedback.id,
        )
        db.add(rule_feedback_submission)
    db.commit()

    return feedbacks


def generate_evaluative_mode_feedbacks_and_fulfillments(
    db: Session,
    rules: list,
    llm_rule_evaluations: list[LLMRuleEvaluation],
    submission: Submission,
) -> None:
    llm_evaluations_by_rule = {e.rule_id: e for e in llm_rule_evaluations}

    logger.info(f"Creating feedback and fulfillment objects for {len(rules)} rules...")
    for rule in rules:
        llm_evaluation = llm_evaluations_by_rule.get(rule.rule_id)
        logger.info(f"Matching LLM rule evaluation for rule {rule.rule_id}: {llm_evaluation}")
        grade = llm_evaluation.grade if llm_evaluation else None
        feedback = Feedback(
            feedback_text=llm_evaluation.grade_explanation if llm_evaluation else "",
            rule_id=rule.rule_id,
        )
        db.add(feedback)
        db.flush()
        db.add(
            RuleFeedbackSubmission(
                rule_id=rule.rule_id,
                submission_id=submission.id,
                feedback_id=feedback.id,
            )
        )
        db.add(
            Fulfillment(
                initial_fulfillment_value=grade if grade in (0, 1, 2) else None,
                feedback_id=feedback.id,
                submission_id=submission.id,
            )
        )


def create_interactive_mode_feedbacks_response(
    db: Session,
    feedbacks: list[Feedback],
) -> list[InteractiveFeedbackResponse]:
    feedback_responses = []
    for feedback in feedbacks:
        rule: Rule = retrieve_by_id(db, feedback.rule_id)
        feedback_responses.append(
            InteractiveFeedbackResponse(
                id=feedback.id,
                feedback_text=feedback.feedback_text,
                initially_fulfilled=feedback.initially_fulfilled,
                rule_name=rule.name,
                rule_description=rule.description,
                additional_feedback_text=feedback.additional_text,
                is_valid=feedback.is_valid,
            )
        )
    return feedback_responses


def _create_interactive_feedback_text(llm_rule_feedback: LLMRuleFeedback):
    return (
        llm_rule_feedback.validity_explanation
        if llm_rule_feedback.validity_explanation
        else llm_rule_feedback.correction + llm_rule_feedback.correction_explanation
    )


def _is_rule_initially_fulfilled(llm_rule_feedback: LLMRuleFeedback):
    return True if llm_rule_feedback.validity_explanation else False
