from sqlalchemy.orm import Session
from ..llm.schema import LLMRuleFeedback
from ..models.feedback import Feedback
from ..models.submission import Submission
from ..models.rule_feedback_submission import RuleFeedbackSubmission
from ..models.rule import Rule
from ..schemas.feedback import InteractiveFeedbackResponse
from ..repository.rule import retrieve_by_id
from ..utils.logger import logger


def generate_initial_interactive_mode_feedbacks(
    db: Session,
    rules: list,
    llm_rule_feedbacks: list[LLMRuleFeedback],
    submission: Submission,
) -> list[Feedback]:
    feedbacks: list[Feedback] = []
    logger.info("Creating feedback objects...")
    for rule_id, rule_name, _ in rules:
        logger.info(f"Rule name {rule_name}")
        for llm_rule_feedback in llm_rule_feedbacks:
            if rule_name == llm_rule_feedback.rule_name:
                feedback = Feedback(
                    feedback_text=_create_feedback_text(llm_rule_feedback),
                    initially_fulfilled=_is_rule_initially_fulfilled(llm_rule_feedback),
                    rule_id=rule_id,
                )
                db.add(feedback)
                feedbacks.append(feedback)
    # flush will add all of the autogenerated fields to our list before commiting
    db.flush()
    db.commit()

    logger.info("Creating rule feedback submission objects...")
    for feedback in feedbacks:
        rule_feedback_submission = RuleFeedbackSubmission(
            rule_id=feedback.rule_id,
            submission_id=submission.id,
            feedback_id=feedback.id,
        )
        db.add(rule_feedback_submission)
    db.commit()

    return feedbacks


def create_interactive_mode_feedbacks_response(
    db: Session,
    feedbacks: list[Feedback],
) -> list[InteractiveFeedbackResponse]:
    feedback_responses = []
    for feedback in feedbacks:
        rule: Rule = retrieve_by_id(db, feedback.rule_id)
        feedback_responses.append(
            InteractiveFeedbackResponse(
                id=feedback.id,
                feedback_text=feedback.feedback_text,
                initially_fulfilled=feedback.initially_fulfilled,
                rule_name=rule.name,
                rule_description=rule.description,
                additional_text=feedback.additional_text,
            )
        )
    return feedback_responses


def _create_feedback_text(llm_rule_feedback: LLMRuleFeedback):
    return (
        llm_rule_feedback.validity_explanation
        if llm_rule_feedback.validity_explanation
        else llm_rule_feedback.correction + llm_rule_feedback.correction_explanation
    )


def _is_rule_initially_fulfilled(llm_rule_feedback: LLMRuleFeedback):
    return True if llm_rule_feedback.validity_explanation else False
