"""Add prompt template for updating summarised student knowledge

Revision ID: 0962738b39f0
Revises: 728f3ec9c399
Create Date: 2025-06-19 09:44:48.878539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0962738b39f0"
down_revision: Union[str, None] = "728f3ec9c399"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "INSERT INTO academic_writing_schema.prompt_template (system_text, user_text, description, purpose) "
        "VALUES "
        "('', "
        "'Nakon što si oformirao prethodno-spomenuti JSON vezan za pravila, potrebno je da u taj JSON dodaš još jedno polje.\n"
        "To polje treba da ima ključ ```updated_knowledge``` i njegova vrednost treba da predstavlja ažurirano znanje studenta na osnovu:\n"
        "1) njegovog prethodnog znanja što sam ti prosledio u system prompt-u i"
        "2) zaključaka o kvalitetu pisanja koje si izvukao na osnovu pravila.',"
        "'Prompt template used for the update of the summarised student knowledge.',"
        "'Knowledge Summarisation')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM academic_writing_schema.prompt_template
        WHERE purpose = 'Knowledge Summarisation'
        """
    )


# ### end Alembic commands ###
