"""Add prompt template for updating summarised student knowledge

Revision ID: 0962738b39f0
Revises: 728f3ec9c399
Create Date: 2025-06-19 09:44:48.878539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0962738b39f0"
down_revision: Union[str, None] = "728f3ec9c399"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "INSERT INTO academic_writing_schema.prompt_template (system_text, user_text, description, purpose) "
        "VALUES "
        "('', "
        "'Nakon što si oformirao prethodno-spomenuti JSON vezan za pravila, potrebno je da u taj JSON dodaš još jedno polje.\n"
        "To polje treba da ima ključ ```updated_knowledge``` i njegova vrednost treba da predstavlja ažurirano znanje studenta na osnovu:\n"
        "1) njegovog prethodnog znanja što sam ti prosledio u system prompt-u i"
        "2) zaključaka o kvalitetu pisanja koje si izvukao na osnovu pravila.',"
        "'Prompt template used for the update of the summarised student knowledge for the initial interactive mode.',"
        "'Knowledge Summarisation Initial Interactive')"
    )
    op.execute(
        "INSERT INTO academic_writing_schema.prompt_template (system_text, user_text, description, purpose) "
        "VALUES "
        "('Ti si recenzent koji je prethodno revidirao naučni rad.\n\n"
        "Potrebno je da odgovori budu formalni i da na osnovu unesenog teksta i svog prethodnog odgovora, koje ću ti priložiti, dodatno obrazložiš razmišljanje iza istog.\n"
        "U svojim odgovorima koristi ekavicu ili ijekavicu srpskog jezika, u zavisnosti od toga koji dijalekt uočiš u tekstu priloženog naučnog rada.\n"
        "Takođe, prilikom davanja dodatnog objašnjenja, potrebno je da uzmeš u obzir i prethodno-uočene studentske šablone rada, koji su opisani ispod ove rečenice:\n\n"
        "{student_knowledge}', "
        "'Prvo ću ti priložiti tekst na osnovu kojeg si dao povratnu informaciju studentu, pravilo koje si revidirao, a zatim i tvoju povratnu informaciju.\n"
        "Potrebno je da mi vratiš detaljnije obrazloženje te povratne informacije. Očekujem da ćeš mi ovo vratiti u JSON formatu, gde će ključ biti additional_explanation, a vrednost će biti tvoje dodatno obrazloženje.\n\n"
        "Tekst:\n"
        "{text}\n\n"
        "Pravilo:\n"
        "{rule}\n\n"
        "Tvoja povratna informacija:\n"
        "{feedback}\n\n',"
        "'Prompt template used for the retrieval of the additional feedback information in the interactive mode.',"
        "'Additional Interactive')"
    )
    op.execute(
        "INSERT INTO academic_writing_schema.prompt_template (system_text, user_text, description, purpose) "
        "VALUES "
        "('', "
        "'Nakon što si oformirao prethodno-spomenuti JSON vezan za dodatno objašnjenje, potrebno je da u taj JSON dodaš još jedno polje.\n"
        "To polje treba da ima ključ ```updated_knowledge``` i njegova vrednost treba da predstavlja ažurirano znanje studenta na osnovu:\n"
        "1) njegovog prethodnog znanja što sam ti prosledio u system prompt-u i "
        "2) informaciji da je zatražio dodatno pojašnjenje za neko pravilo."
        "Studentovo prethodno znanje treba da ima veći uticaj na celokupno ažurirano znanje u odnosu na informaciju o traženju dodatnog pojašnjenja.',"
        "'Prompt template used for the update of the summarised student knowledge in the additional interactive mode.',"
        "'Knowledge Summarisation Additional Interactive')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
        DELETE FROM academic_writing_schema.prompt_template
        WHERE purpose = 'Knowledge Summarisation Additional Interactive'
        """
    )
    op.execute(
        """
        DELETE FROM academic_writing_schema.prompt_template
        WHERE purpose = 'Additional Interactive'
        """
    )
    op.execute(
        """
        DELETE FROM academic_writing_schema.prompt_template
        WHERE purpose = 'Knowledge Summarisation Initial Interactive'
        """
    )


# ### end Alembic commands ###
