"""Extend submission model and add evaluation prompts

Revision ID: 1dc39071d54a
Revises: 0962738b39f0
Create Date: 2025-07-08 06:41:56.342369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1dc39071d54a"
down_revision: Union[str, None] = "0962738b39f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission",
        sa.Column(
            "graded", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        schema="academic_writing_schema",
    )
    op.execute(
        "INSERT INTO academic_writing_schema.prompt_template (system_text, user_text, description, purpose) "
        "VALUES "
        "('Ti si recenzent koji treba da oceni naučne radove i da da razlog iza datih ocena.\n\n"
        "Potrebno je da odgovori budu formalni i da na osnovu pravila, koja ću ti priložiti, revidiraš uneseni tekst i daš ocenu za svako pravilo.\n"
        "Potrebno je da svako pravilo oceniš sa ocenom 0, 1 ili 2. 2 predstavlja potpuno poštovanje pravila, 1 predstavlja delimično poštovanje pravila (ekvivalent mašenju pravila dva puta, gde ga je moguće više puta promašiti), a 0 predstavlja potpuno mašenje pravila (ekvivalent mašenju pravila tri ili više puta, gde ga je moguće više puta omašiti)."
        "U svojim odgovorima koristi ekavicu ili ijekavicu srpskog jezika, u zavisnosti od toga koji dijalekt uočiš u tekstu priloženog naučnog rada.\n"
        "Takođe, prilikom davanja obrazloženja iza ocena, potrebno je da prilagodiš odgovor u odnosu na prethodno-uočene studentske šablone rada, koji su opisani ispod ove rečenice:\n\n{student_knowledge}', "
        "'Prvo ću ti priložiti sva pravila na osnovu kojih treba da oceniš tekst, a zatim i tekst koji treba da oceniš.\n"
        "Tvoj odgovor treba da prikaže ocenu i razloge iza te ocene za svako pravilo. U slučaju da ocena nije 2, potrebno je i da navedeš konkretne rečenice iz teksta gde pravilo odstupa u obrazloženju.\n"
        "Za svako pravilo koje se nalazi ispod `Pravila`, tvoj odgovor treba da ima sledeći šablon i ništa van njega ne treba da postoji. Ponavljam, **moraš** mi vratiti odgovor po sledećem šablonu:\n\n"
        "Naziv pravila koje se ocenjuje (Izvuci ove nazive iz `Pravila`):\n"
        "Ocena:\n"
        "Obrazloženje ocene:\n\n"
        "Pravila:\n',"
        "'Prompt template used for the evaluative app mode.',"
        "'Evaluative')"
    )
    op.execute(
        "INSERT INTO academic_writing_schema.prompt_template (system_text, user_text, description, purpose) "
        "VALUES "
        "('Ti si recenzent koji je prethodno ocenio naučni rad na osnovu definisanih pravila. Sada je samo potrebno da ažuriraš uočeno znanje studenta na osnovu prethodnog uočenog znanja i novonastalih zaključaka.', "
        "'Potrebno je da oformiraš JSON, koji će imati ključ ```updated_knowledge``` i njegova vrednost treba da predstavlja ažurirano znanje studenta na osnovu:.\n"
        "1) njegovog prethodnog znanja, koje je: {summarised_knowledge} i"
        "2) zaključaka koji su izvedeni iz evaluacije: {evaluative_conclusion}. Uzmi u obzir da je najmanja ocena po pravilu 0, a najveća 2.',"
        "'Prompt template used for the update of the summarised student knowledge in the evaluative mode.',"
        "'Knowledge Summarisation Evaluative')"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM academic_writing_schema.prompt_template
        WHERE purpose = 'Knowledge Summarisation Evaluative'
        """
    )
    op.execute(
        """
        DELETE FROM academic_writing_schema.prompt_template
        WHERE purpose = 'Evaluative'
        """
    )
    op.drop_column("submission", "graded", schema="academic_writing_schema")
    # ### end Alembic commands ###
