"""Change submissions points to percentage

Revision ID: aeb6ff6a7fa2
Revises: 44bc22caeda0
Create Date: 2025-07-12 08:48:57.237195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb6ff6a7fa2'
down_revision: Union[str, None] = '44bc22caeda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('achieved_points_percentage', sa.Float(), nullable=True), schema='academic_writing_schema')
    op.drop_column('submission', 'achieved_points', schema='academic_writing_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('achieved_points', sa.INTEGER(), autoincrement=False, nullable=True), schema='academic_writing_schema')
    op.drop_column('submission', 'achieved_points_percentage', schema='academic_writing_schema')
    # ### end Alembic commands ###
