"""Add assigned to ta field

Revision ID: 44bc22caeda0
Revises: 923e544fbe52
Create Date: 2025-07-11 11:40:28.634619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44bc22caeda0"
down_revision: Union[str, None] = "923e544fbe52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("assigned_to_ta", sa.Integer(), nullable=True),
        schema="academic_writing_schema",
    )
    op.create_foreign_key(
        "assigned_to_ta_fk",
        "user",
        "user",
        ["assigned_to_ta"],
        ["id"],
        source_schema="academic_writing_schema",
        referent_schema="academic_writing_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "assigned_to_ta_fk",
        "user",
        schema="academic_writing_schema",
        type_="foreignkey",
    )
    op.drop_column("user", "assigned_to_ta", schema="academic_writing_schema")
    # ### end Alembic commands ###
