"""Add initial student knowledge prompt

Revision ID: 9812170dfeec
Revises: 3e01bdc1a41c
Create Date: 2025-10-22 08:14:56.014964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9812170dfeec"
down_revision: Union[str, None] = "3e01bdc1a41c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "INSERT INTO academic_writing_schema.prompt_template (system_text, user_text, description, purpose) "
        "VALUES "
        "('Ti si recenzent koji će ubuduće revidirati naučne radove.\n\n"
        "Potrebno je da oformiraš inicijalno studentsko znanje u par rečenica na osnovu podataka sa pretesta koje ću ti priložiti. Pretest je rađen na unapred-napisanom poglavlju naučnog rada, a prisutne ocene reflektuju koliko je kvalitetno student obradio svako od pravila.', "
        "'Priložiću ti sledeće informacije:\n"
        "1) Nazive pravila na osnovu kojih je evaluiran pretest,\n"
        "2) Opise prethodno spomenutih pravila i \n"
        "3) Dodeljenu ocenu za svako pravilo, gde ta ocena reflektuje koliko je kvalitetno student obradio to pravilo i ona može biti 0 (skroz je netačan odgovor), 1 (odgovor je delimično tačan) i 2 (odgovor je u potpunosti tačan).\n"
        "Na osnovu ovih informacija, potrebno je da mi vratiš sažeto inicijalno znanje studenta u par rečenica."
        "Ispod je za svako pravilo priloženo: naziv pravila, opis pravila i ocena dodeljena za to pravilo:\n', "
        "'Prompt template used for the creation of the initial student knowledge.',"
        "'Initial Student Knowledge Creation')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM academic_writing_schema.prompt_template
        WHERE purpose = 'Initial Student Knowledge Creation'
        """
    )
    # ### end Alembic commands ###
