"""Add name to the group

Revision ID: 1e51a33a7bb1
Revises: a4c3135cf103
Create Date: 2025-05-27 19:19:31.834646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e51a33a7bb1'
down_revision: Union[str, None] = 'a4c3135cf103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sa.String(), nullable=True), schema='academic_writing_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'name', schema='academic_writing_schema')
    # ### end Alembic commands ###
