"""Add assignment objects

Revision ID: 0c9278a73c0b
Revises: aeb6ff6a7fa2
Create Date: 2025-07-18 10:29:56.197630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c9278a73c0b"
down_revision: Union[str, None] = "aeb6ff6a7fa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("end_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("submission_mode_id", sa.Integer(), nullable=True),
        sa.Column("chapter_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["academic_writing_schema.chapter.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_mode_id"],
            ["academic_writing_schema.submission_mode.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="academic_writing_schema",
    )
    op.create_table(
        "assignment_group",
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["academic_writing_schema.assignment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["academic_writing_schema.group.id"],
        ),
        sa.PrimaryKeyConstraint("assignment_id", "group_id"),
        schema="academic_writing_schema",
    )
    op.add_column(
        "submission",
        sa.Column("assignment_id", sa.Integer(), nullable=True),
        schema="academic_writing_schema",
    )
    op.drop_constraint(
        "submission_chapter_id_fkey",
        "submission",
        schema="academic_writing_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "submission",
        "assignment",
        ["assignment_id"],
        ["id"],
        source_schema="academic_writing_schema",
        referent_schema="academic_writing_schema",
    )
    op.drop_column("submission", "chapter_id", schema="academic_writing_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission",
        sa.Column("chapter_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="academic_writing_schema",
    )
    op.drop_constraint(
        None, "submission", schema="academic_writing_schema", type_="foreignkey"
    )
    op.create_foreign_key(
        "submission_chapter_id_fkey",
        "submission",
        "chapter",
        ["chapter_id"],
        ["id"],
        source_schema="academic_writing_schema",
        referent_schema="academic_writing_schema",
    )
    op.drop_column("submission", "assignment_id", schema="academic_writing_schema")
    op.drop_table("assignment_group", schema="academic_writing_schema")
    op.drop_table("assignment", schema="academic_writing_schema")
    # ### end Alembic commands ###
