"""Add new fields for evaluative mode

Revision ID: 923e544fbe52
Revises: 1dc39071d54a
Create Date: 2025-07-11 07:54:51.945162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923e544fbe52'
down_revision: Union[str, None] = '1dc39071d54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('final_feedback_text', sa.String(), nullable=True), schema='academic_writing_schema')
    op.add_column('fulfillment', sa.Column('initial_fulfillment_value', sa.Integer(), nullable=True), schema='academic_writing_schema')
    op.add_column('fulfillment', sa.Column('final_fulfillment_value', sa.Integer(), nullable=True), schema='academic_writing_schema')
    op.drop_column('fulfillment', 'fulfillment_value', schema='academic_writing_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fulfillment', sa.Column('fulfillment_value', sa.INTEGER(), autoincrement=False, nullable=True), schema='academic_writing_schema')
    op.drop_column('fulfillment', 'final_fulfillment_value', schema='academic_writing_schema')
    op.drop_column('fulfillment', 'initial_fulfillment_value', schema='academic_writing_schema')
    op.drop_column('feedback', 'final_feedback_text', schema='academic_writing_schema')
    # ### end Alembic commands ###
