"""Add is_deleted to group

Revision ID: daad5b46aa4d
Revises: 3478f5617010
Create Date: 2026-07-22 19:05:15.475517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daad5b46aa4d'
down_revision: Union[str, None] = '3478f5617010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='academic_writing_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_deleted', schema='academic_writing_schema')
    # ### end Alembic commands ###
