"""Add course

Revision ID: 06612e6c11b6
Revises: e03a74b56b33
Create Date: 2026-06-25 11:19:49.978880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06612e6c11b6"
down_revision: Union[str, None] = "e03a74b56b33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM academic_writing_schema.chapter_grading_aspect")
    op.execute("DELETE FROM academic_writing_schema.rule")
    op.execute("DELETE FROM academic_writing_schema.grading_aspect")

    op.create_table(
        "language",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="academic_writing_schema",
    )
    op.create_table(
        "rule_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("percentage_of_points_in_assignment", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="academic_writing_schema",
    )
    op.create_table(
        "course",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("max_amount_of_points", sa.Float(), nullable=True),
        sa.Column("feedback_language_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("end_date", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feedback_language_id"],
            ["academic_writing_schema.language.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="academic_writing_schema",
    )
    op.create_table(
        "assignment_rule_group",
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("rule_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["academic_writing_schema.assignment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_group_id"],
            ["academic_writing_schema.rule_group.id"],
        ),
        sa.PrimaryKeyConstraint("assignment_id", "rule_group_id"),
        schema="academic_writing_schema",
    )
    op.create_table(
        "course_group",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["academic_writing_schema.course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["academic_writing_schema.group.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "group_id"),
        schema="academic_writing_schema",
    )
    op.create_table(
        "course_submission_language",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["academic_writing_schema.course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["academic_writing_schema.language.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "language_id"),
        schema="academic_writing_schema",
    )
    op.create_table(
        "user_course_points",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("achieved_points", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["academic_writing_schema.course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["academic_writing_schema.user.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "user_id"),
        schema="academic_writing_schema",
    )
    op.drop_table("assignment_group", schema="academic_writing_schema")
    op.execute(
        "DROP TABLE IF EXISTS academic_writing_schema.chapter_grading_aspect CASCADE"
    )
    op.execute("DROP TABLE IF EXISTS academic_writing_schema.grading_aspect CASCADE")
    op.add_column(
        "assignment",
        sa.Column("percentage_of_points_in_course", sa.Float(), nullable=True),
        schema="academic_writing_schema",
    )
    op.add_column(
        "rule",
        sa.Column("user_description", sa.String(), nullable=True),
        schema="academic_writing_schema",
    )
    op.add_column(
        "rule",
        sa.Column("rule_group_id", sa.Integer(), nullable=True),
        schema="academic_writing_schema",
    )
    op.add_column(
        "rule",
        sa.Column("prompt_description", sa.String(), nullable=True),
        schema="academic_writing_schema",
    )
    op.execute(
        "ALTER TABLE academic_writing_schema.rule DROP CONSTRAINT IF EXISTS rule_grading_aspect_id_fkey"
    )
    op.create_foreign_key(
        "rule_rule_group_id_fkey",
        "rule",
        "rule_group",
        ["rule_group_id"],
        ["id"],
        source_schema="academic_writing_schema",
        referent_schema="academic_writing_schema",
    )
    op.add_column(
        "assignment",
        sa.Column("course_id", sa.Integer(), nullable=True),
        schema="academic_writing_schema",
    )
    op.create_foreign_key(
        "assignment_course_id_fkey",
        "assignment",
        "course",
        ["course_id"],
        ["id"],
        source_schema="academic_writing_schema",
        referent_schema="academic_writing_schema",
    )
    op.drop_column("rule", "description", schema="academic_writing_schema")
    op.drop_column("rule", "grading_aspect_id", schema="academic_writing_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "assignment_course_id_fkey",
        "assignment",
        schema="academic_writing_schema",
        type_="foreignkey",
    )
    op.drop_column("assignment", "course_id", schema="academic_writing_schema")
    op.create_table(
        "grading_aspect",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('academic_writing_schema.grading_aspect_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "max_amount_of_points", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="grading_aspect_pkey"),
        schema="academic_writing_schema",
        postgresql_ignore_search_path=False,
    )
    op.add_column(
        "rule",
        sa.Column(
            "grading_aspect_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        schema="academic_writing_schema",
    )
    op.add_column(
        "rule",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="academic_writing_schema",
    )
    op.drop_constraint(
        "rule_rule_group_id_fkey",
        "rule",
        schema="academic_writing_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "rule_grading_aspect_id_fkey",
        "rule",
        "grading_aspect",
        ["grading_aspect_id"],
        ["id"],
        source_schema="academic_writing_schema",
        referent_schema="academic_writing_schema",
    )
    op.drop_column("rule", "prompt_description", schema="academic_writing_schema")
    op.drop_column("rule", "rule_group_id", schema="academic_writing_schema")
    op.drop_column("rule", "user_description", schema="academic_writing_schema")
    op.drop_column(
        "assignment", "percentage_of_points_in_course", schema="academic_writing_schema"
    )
    op.create_table(
        "chapter_grading_aspect",
        sa.Column("chapter_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "grading_aspect_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["academic_writing_schema.chapter.id"],
            name="chapter_grading_aspect_chapter_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["grading_aspect_id"],
            ["academic_writing_schema.grading_aspect.id"],
            name="chapter_grading_aspect_grading_aspect_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "chapter_id", "grading_aspect_id", name="chapter_grading_aspect_pkey"
        ),
        schema="academic_writing_schema",
    )
    op.create_table(
        "assignment_group",
        sa.Column("assignment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["academic_writing_schema.assignment.id"],
            name="assignment_group_assignment_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["academic_writing_schema.group.id"],
            name="assignment_group_group_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "assignment_id", "group_id", name="assignment_group_pkey"
        ),
        schema="academic_writing_schema",
    )
    op.drop_table("user_course_points", schema="academic_writing_schema")
    op.drop_table("course_submission_language", schema="academic_writing_schema")
    op.drop_table("course_group", schema="academic_writing_schema")
    op.drop_table("assignment_rule_group", schema="academic_writing_schema")
    op.drop_table("course", schema="academic_writing_schema")
    op.drop_table("rule_group", schema="academic_writing_schema")
    op.drop_table("language", schema="academic_writing_schema")
    # ### end Alembic commands ###
