"""Add course instructor

Revision ID: 3478f5617010
Revises: 33ce80d3aa8b
Create Date: 2026-07-21 15:40:46.631396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3478f5617010"
down_revision: Union[str, None] = "33ce80d3aa8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_instructor",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["academic_writing_schema.course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["academic_writing_schema.user.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "instructor_id"),
        schema="academic_writing_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course_instructor", schema="academic_writing_schema")
    # ### end Alembic commands ###
