"""Update user prompts for feedback generation

Revision ID: 2bd052143563
Revises: 65423653cca8
Create Date: 2026-02-19 11:46:36.172801

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2bd052143563"
down_revision: Union[str, None] = "65423653cca8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE academic_writing_schema.prompt_template "
        "SET user_text='Prvo ću ti priložiti sva pravila na osnovu kojih treba da oceniš tekst, a zatim i tekst koji treba da oceniš.\n"
        "Ponavljam, **VEOMA BITNO**, za svako pravilo koje sam ti naveo je potrebno da vratiš odgovarajuću strukturu. Proveri da li si revidirao tekst po svakom pravilu.\n"
        "Tvoj odgovor treba da prikaže ocenu i razloge iza te ocene za svako pravilo. U slučaju da ocena nije 2, potrebno je dodatno da navedeš konkretne rečenice iz teksta zbog kojih je data niža ocena.\n"
        "Za svako pravilo koje se nalazi ispod `Pravila`, tvoj odgovor treba da ima sledeći šablon i ništa van njega ne treba da postoji. Ponavljam, **moraš** mi vratiti odgovor po sledećem šablonu:\n\n"
        "Naziv pravila koje se ocenjuje (Izvuci ove nazive iz `Pravila`):\n"
        "Ocena:\n"
        "Obrazloženje ocene:\n\n"
        "Pravila:\n' "
        "WHERE purpose='Evaluative'"
    )
    op.execute(
        "UPDATE academic_writing_schema.prompt_template "
        "SET user_text='Prvo ću ti priložiti sva pravila koja treba da budu ispoštovana, a zatim i tekst koji treba da ispraviš.\n"
        "Ponavljam, **VEOMA BITNO**, za svako pravilo koje sam ti naveo je potrebno da vratiš odgovarajuću strukturu. Proveri da li si revidirao tekst po svakom pravilu.\n"
        "Tvoj odgovor treba da prikaže predloge ispravki, razloge predloga ispravki teksta za svako pravilo, kao i rečenice iz teksta zbog kojih smatraš da su ispravke potrebne.\n"
        "Ukoliko smatraš da je pravilo ispoštovano 90%, navedi da je ono ispoštovano umesto ispravke\n"
        "Za svako pravilo koje se nalazi ispod `Pravila`, tvoj odgovor treba da ima sledeći šablon i ništa van njega ne treba da postoji. Ponavljam, **moraš** mi vratiti odgovor po sledećim šablonima:\n\n"
        "(Ako si siguran da je ispravno manje od 90%)\n"
        "Naziv pravila koje se ispravlja (Izvuci ove nazive iz `Pravila`):\n"
        "Ispravka:\n"
        "Obrazloženje ispravke:\n\n"
        "(Ako si siguran da je ispravno više od ili jednako 90%)\n"
        "Naziv pravila koje se ispravlja (Izvuci ove nazive iz `Pravila`):\n"
        "Obrazloženje validnosti:\n"
        "Pravila:\n' "
        "WHERE purpose='Initial Interactive'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE academic_writing_schema.prompt_template "
        "SET user_text='Prvo ću ti priložiti sva pravila na osnovu kojih treba da oceniš tekst, a zatim i tekst koji treba da oceniš.\n"
        "Tvoj odgovor treba da prikaže ocenu i razloge iza te ocene za svako pravilo. U slučaju da ocena nije 2, potrebno je dodatno da navedeš konkretne rečenice iz teksta zbog kojih je data niža ocena.\n"
        "Za svako pravilo koje se nalazi ispod `Pravila`, tvoj odgovor treba da ima sledeći šablon i ništa van njega ne treba da postoji. Ponavljam, **moraš** mi vratiti odgovor po sledećem šablonu:\n\n"
        "Naziv pravila koje se ocenjuje (Izvuci ove nazive iz `Pravila`):\n"
        "Ocena:\n"
        "Obrazloženje ocene:\n\n"
        "Pravila:\n' "
        "WHERE purpose='Evaluative'"
    )
    op.execute(
        "UPDATE academic_writing_schema.prompt_template "
        "SET user_text='Prvo ću ti priložiti sva pravila koja treba da budu ispoštovana, a zatim i tekst koji treba da ispraviš.\n"
        "Tvoj odgovor treba da prikaže predloge ispravki, razloge predloga ispravki teksta za svako pravilo, kao i rečenice iz teksta zbog kojih smatraš da su ispravke potrebne.\n"
        "Ukoliko smatraš da je pravilo ispoštovano 90%, navedi da je ono ispoštovano umesto ispravke\n"
        "Za svako pravilo koje se nalazi ispod `Pravila`, tvoj odgovor treba da ima sledeći šablon i ništa van njega ne treba da postoji. Ponavljam, **moraš** mi vratiti odgovor po sledećim šablonima:\n\n"
        "(Ako si siguran da je ispravno manje od 90%)\n"
        "Naziv pravila koje se ispravlja (Izvuci ove nazive iz `Pravila`):\n"
        "Ispravka:\n"
        "Obrazloženje ispravke:\n\n"
        "(Ako si siguran da je ispravno više od ili jednako 90%)\n"
        "Naziv pravila koje se ispravlja (Izvuci ove nazive iz `Pravila`):\n"
        "Obrazloženje validnosti:\n"
        "Pravila:\n' "
        "WHERE purpose='Initial Interactive'"
    )
    # ### end Alembic commands ###
