"""Add submission status

Revision ID: 3e01bdc1a41c
Revises: ee86bb9a22c9
Create Date: 2025-08-26 09:14:28.681208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e01bdc1a41c'
down_revision: Union[str, None] = 'ee86bb9a22c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('status', sa.String(), nullable=True), schema='academic_writing_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'status', schema='academic_writing_schema')
    # ### end Alembic commands ###
