"""Update unique name for group object

Revision ID: 4d53873c2393
Revises: 1e51a33a7bb1
Create Date: 2025-05-28 13:04:48.368205

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d53873c2393'
down_revision: Union[str, None] = '1e51a33a7bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='academic_writing_schema')
    op.create_unique_constraint('uq_group_name', 'group', ['name'], schema='academic_writing_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_group_name', 'group', schema='academic_writing_schema', type_='unique')
    op.alter_column('group', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='academic_writing_schema')
    # ### end Alembic commands ###
