"""Extend prompt template model

Revision ID: 5ccaa466ac0c
Revises: 8aad7d1f3c07
Create Date: 2025-05-30 14:05:19.284430

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ccaa466ac0c"
down_revision: Union[str, None] = "8aad7d1f3c07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt_template",
        sa.Column("system_text", sa.String(), nullable=True),
        schema="academic_writing_schema",
    )
    op.add_column(
        "prompt_template",
        sa.Column("user_text", sa.String(), nullable=True),
        schema="academic_writing_schema",
    )
    op.add_column(
        "prompt_template",
        sa.Column("purpose", sa.String(), nullable=True),
        schema="academic_writing_schema",
    )
    op.drop_column("prompt_template", "text", schema="academic_writing_schema")

    # TODO - Add a predefined prompt template
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt_template",
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="academic_writing_schema",
    )
    op.drop_column("prompt_template", "purpose", schema="academic_writing_schema")
    op.drop_column("prompt_template", "user_text", schema="academic_writing_schema")
    op.drop_column("prompt_template", "system_text", schema="academic_writing_schema")
    # ### end Alembic commands ###
