"""Extend prompt template model

Revision ID: 5ccaa466ac0c
Revises: 8aad7d1f3c07
Create Date: 2025-05-30 14:05:19.284430

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ccaa466ac0c"
down_revision: Union[str, None] = "8aad7d1f3c07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt_template",
        sa.Column("system_text", sa.String(), nullable=True),
        schema="academic_writing_schema",
    )
    op.add_column(
        "prompt_template",
        sa.Column("user_text", sa.String(), nullable=True),
        schema="academic_writing_schema",
    )
    op.add_column(
        "prompt_template",
        sa.Column("purpose", sa.String(), nullable=True),
        schema="academic_writing_schema",
    )
    op.drop_column("prompt_template", "text", schema="academic_writing_schema")

    op.execute(
        "INSERT INTO academic_writing_schema.prompt_template (system_text, user_text, description, purpose) "
        "VALUES "
        "('Ti si recenzent koji treba da revidira naučne radove.\n\n"
        "Potrebno je da odgovori budu formalni i da na osnovu pravila, koja ću ti priložiti, revidiraš uneseni tekst.\n"
        "U svojim odgovorima koristi ekavicu ili ijekavicu srpskog jezika, u zavisnosti od toga koji dijalekt uočiš u tekstu priloženog naučnog rada.\n"
        "Takođe, prilikom revidiranja, potrebno je da uzmeš u obzir i prethodno-uočene studentske šablone rada, koji su opisani ispod ove rečenice:\n\n', "
        "'Prvo ću ti priložiti sva pravila koja treba da budu ispoštovana, a zatim i tekst koji treba da ispraviš.\n"
        "Tvoj odgovor treba da prikaže predloge ispravke i razloge predloga ispravki teksta za svako pravilo.\n"
        "Ukoliko smatraš da je pravilo ispoštovano 90%, navedi da je ono ispoštovano umesto ispravke\n"
        "Za svako pravilo koje se nalazi ispod `Pravila`, tvoj odgovor treba da ima sledeći šablon i ništa van njega ne treba da postoji.\n\n"
        "(Ako si siguran da je ispravno manje od 90%)\n"
        "Naziv pravila koje se ispravlja (Izvuci ove nazive iz `Pravila`):\n"
        "Ispravka:\n"
        "Obrazloženje ispravke:\n\n"
        "(Ako si siguran da je ispravno više od ili jednako 90%)\n"
        "Naziv pravila koje se ispravlja (Izvuci ove nazive iz `Pravila`):\n"
        "Obrazloženje validnosti:\n"
        "Pravila:',"
        "'Prompt template used for the initial interaction within the interactive app mode.',"
        "'Initial Interactive')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM academic_writing_schema.prompt_template
        WHERE purpose = 'Initial Interactive'
        """
    )
    op.add_column(
        "prompt_template",
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="academic_writing_schema",
    )
    op.drop_column("prompt_template", "purpose", schema="academic_writing_schema")
    op.drop_column("prompt_template", "user_text", schema="academic_writing_schema")
    op.drop_column("prompt_template", "system_text", schema="academic_writing_schema")
    # ### end Alembic commands ###
