"""Modify feedback and fulfillment tables

Revision ID: 728f3ec9c399
Revises: 5ccaa466ac0c
Create Date: 2025-06-19 08:55:43.823057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "728f3ec9c399"
down_revision: Union[str, None] = "5ccaa466ac0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "feedback_fulfillment_id_fkey",
        "feedback",
        schema="academic_writing_schema",
        type_="foreignkey",
    )
    op.drop_column("feedback", "fulfillment_id", schema="academic_writing_schema")
    op.add_column(
        "fulfillment",
        sa.Column("feedback_id", sa.Integer(), nullable=True),
        schema="academic_writing_schema",
    )
    op.drop_constraint(
        "fulfillment_rule_id_fkey",
        "fulfillment",
        schema="academic_writing_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_feedback",
        "fulfillment",
        "feedback",
        ["feedback_id"],
        ["id"],
        source_schema="academic_writing_schema",
        referent_schema="academic_writing_schema",
    )
    op.drop_column("fulfillment", "rule_id", schema="academic_writing_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fulfillment",
        sa.Column("rule_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="academic_writing_schema",
    )
    op.drop_constraint(
        "fk_feedback",
        "fulfillment",
        schema="academic_writing_schema",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fulfillment_rule_id_fkey",
        "fulfillment",
        "rule",
        ["rule_id"],
        ["id"],
        source_schema="academic_writing_schema",
        referent_schema="academic_writing_schema",
    )
    op.drop_column("fulfillment", "feedback_id", schema="academic_writing_schema")
    op.add_column(
        "feedback",
        sa.Column("fulfillment_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="academic_writing_schema",
    )
    op.create_foreign_key(
        "feedback_fulfillment_id_fkey",
        "feedback",
        "fulfillment",
        ["fulfillment_id"],
        ["id"],
        source_schema="academic_writing_schema",
        referent_schema="academic_writing_schema",
    )
    # ### end Alembic commands ###
