"""Change submission model

Revision ID: 8aad7d1f3c07
Revises: f4b073853503
Create Date: 2025-05-29 14:07:49.230506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aad7d1f3c07'
down_revision: Union[str, None] = 'f4b073853503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('gd_file_id', sa.String(), nullable=True), schema='academic_writing_schema')
    op.add_column('submission', sa.Column('gd_file_link', sa.String(), nullable=True), schema='academic_writing_schema')
    op.drop_column('submission', 'summary', schema='academic_writing_schema')
    op.drop_column('submission', 'file_name', schema='academic_writing_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True), schema='academic_writing_schema')
    op.add_column('submission', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True), schema='academic_writing_schema')
    op.drop_column('submission', 'gd_file_link', schema='academic_writing_schema')
    op.drop_column('submission', 'gd_file_id', schema='academic_writing_schema')
    # ### end Alembic commands ###
