"""Add user and role models

Revision ID: b7608f1ba7a2
Revises:
Create Date: 2024-08-02 08:23:23.126920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7608f1ba7a2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS base_schema")

    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="base_schema",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["base_schema.roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="base_schema",
    )
    op.create_index(
        op.f("ix_base_schema_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="base_schema",
    )

    op.execute("""
        INSERT INTO base_schema.roles(name) VALUES ('GUEST'), ('OWNER'), ('ADMIN')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_base_schema_users_email"), table_name="users", schema="base_schema"
    )
    op.drop_table("users", schema="base_schema")
    op.drop_table("roles", schema="base_schema")
    # ### end Alembic commands ###
