"""Generate initial models

Revision ID: bf8857a3570d
Revises: 
Create Date: 2025-05-22 12:53:20.814514

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf8857a3570d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE SCHEMA IF NOT EXISTS academic_writing_schema")

    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('valid_until', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('prompt_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('submission_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('grading_aspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_amount_of_points', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['academic_writing_schema.chapter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['academic_writing_schema.group.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['academic_writing_schema.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_index(op.f('ix_academic_writing_schema_user_email'), 'user', ['email'], unique=True, schema='academic_writing_schema')
    op.create_table('chapter_grading_aspect',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('grading_aspect_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['academic_writing_schema.chapter.id'], ),
    sa.ForeignKeyConstraint(['grading_aspect_id'], ['academic_writing_schema.grading_aspect.id'], ),
    sa.PrimaryKeyConstraint('chapter_id', 'grading_aspect_id'),
    schema='academic_writing_schema'
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('grading_aspect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grading_aspect_id'], ['academic_writing_schema.grading_aspect.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('achieved_points', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('mode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['academic_writing_schema.chapter.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['academic_writing_schema.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('fulfillment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fulfillment_value', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['academic_writing_schema.rule.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['academic_writing_schema.submission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('historical_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['academic_writing_schema.submission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['academic_writing_schema.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('initially_fulfilled', sa.Boolean(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('fulfillment_id', sa.Integer(), nullable=True),
    sa.Column('additional_text', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fulfillment_id'], ['academic_writing_schema.fulfillment.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['academic_writing_schema.rule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='academic_writing_schema'
    )
    op.create_table('rule_feedback_submission',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['academic_writing_schema.feedback.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['academic_writing_schema.rule.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['academic_writing_schema.submission.id'], ),
    sa.PrimaryKeyConstraint('rule_id', 'submission_id', 'feedback_id'),
    schema='academic_writing_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_feedback_submission', schema='academic_writing_schema')
    op.drop_table('feedback', schema='academic_writing_schema')
    op.drop_table('historical_profile', schema='academic_writing_schema')
    op.drop_table('fulfillment', schema='academic_writing_schema')
    op.drop_table('submission', schema='academic_writing_schema')
    op.drop_table('rule', schema='academic_writing_schema')
    op.drop_table('chapter_grading_aspect', schema='academic_writing_schema')
    op.drop_index(op.f('ix_academic_writing_schema_user_email'), table_name='user', schema='academic_writing_schema')
    op.drop_table('user', schema='academic_writing_schema')
    op.drop_table('grading_aspect', schema='academic_writing_schema')
    op.drop_table('submission_mode', schema='academic_writing_schema')
    op.drop_table('role', schema='academic_writing_schema')
    op.drop_table('prompt_template', schema='academic_writing_schema')
    op.drop_table('group', schema='academic_writing_schema')
    op.drop_table('chapter', schema='academic_writing_schema')
    # ### end Alembic commands ###
