"""Add local file upload

Revision ID: ee86bb9a22c9
Revises: 0c9278a73c0b
Create Date: 2025-07-31 07:22:36.764112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee86bb9a22c9'
down_revision: Union[str, None] = '0c9278a73c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('file_bytes', sa.LargeBinary(), nullable=True), schema='academic_writing_schema')
    op.drop_column('submission', 'gd_file_link', schema='academic_writing_schema')
    op.drop_column('submission', 'gd_file_id', schema='academic_writing_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('gd_file_id', sa.VARCHAR(), autoincrement=False, nullable=True), schema='academic_writing_schema')
    op.add_column('submission', sa.Column('gd_file_link', sa.VARCHAR(), autoincrement=False, nullable=True), schema='academic_writing_schema')
    op.drop_column('submission', 'file_bytes', schema='academic_writing_schema')
    # ### end Alembic commands ###
