"""Add student index

Revision ID: f4b073853503
Revises: 4d53873c2393
Create Date: 2025-05-29 11:34:18.002537

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4b073853503"
down_revision: Union[str, None] = "4d53873c2393"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("index", sa.String(), nullable=True),
        schema="academic_writing_schema",
    )
    op.create_unique_constraint(
        "uq_student_index", "user", ["index"], schema="academic_writing_schema"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_student_index", "user", schema="academic_writing_schema", type_="unique"
    )
    op.drop_column("user", "index", schema="academic_writing_schema")
    # ### end Alembic commands ###
